name: Publish Helm Chart

on:
  workflow_dispatch:
    inputs:
      deploy:
        required: false
        default: false
        type: boolean
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'
      - '.helmignore'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Package and Push Helm Chart
        run: |
          # Set variables
          CHART_DIR="."  # Chart is at root level
          CHART_NAME=$(yq e '.name' ./Chart.yaml)
          CHART_VERSION=$(yq e '.version' ./Chart.yaml)
          
          echo "Chart name: $CHART_NAME"
          echo "Chart version: $CHART_VERSION"
          
          # Package the chart locally
          helm package $CHART_DIR
          
          # Use lowercase repository owner (GitHub Container Registry requirement)
          REPO_OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          
          # Push the chart to GitHub Packages with proper formatting
          echo "Pushing to: oci://ghcr.io/${REPO_OWNER_LC}/charts"
          helm push "${CHART_NAME}-${CHART_VERSION}.tgz" "oci://ghcr.io/${REPO_OWNER_LC}/charts"
